project:
  type: website
  output-dir: docs
  
website:
  title: "Home"
  sidebar: true
  search: true
  navbar:
    right:
      - href: index.qmd
        text: Home
 
format:
  html:
    theme: cosmo
    mainfont: Avenir
    backgroundcolor: seashell
    toc: true
editor: visual
