project:
  type: website
  output-dir: docs
  
website:
  favicon: me.png 
  title: "Andre Dextre"
  sidebar: true
  search: true
  navbar:
    left:
      - href: my_blogs.qmd 
        text: Blogs
      - href: Dextre_Andre_Resume.pdf
        text: Resume
 
format:
  html:
    theme: 
    - mystyles.scss
    page-layout: full
    mainfont: Avenir
    backgroundcolor: seashell
    toc: true
editor: visual
